import { useMemo, useState } from "react";
import { useNavigate, useSearchParams } from "react-router-dom";
import { useMutation, useQuery, useQueryClient } from "@tanstack/react-query";
import { Check, CloudUpload, History, RefreshCw, Search, ShieldOff, Tag, X } from "lucide-react";
import { toast } from "sonner";
import { Amount, ConfirmDialog, Drawer, EmptyState, ErrorNotice, IdentityBadge, PageHeader, TableSkeleton } from "../components/common";
import { useWorkspace } from "../context/WorkspaceContext";
import { fmtDateTime, IDENTITY_LABELS, IDENTITY_METHOD_LABELS, inr, maskPan, pct } from "../lib/format";
import { api, getErrorMessage } from "../services/api";
import type { Customer, IdentityReview } from "../types";

const TABS = ["REVIEW_REQUIRED", "UNMAPPED", "HIGH_CONFIDENCE", "EXACT", "ALL"];
type Pending = { kind: "confirm" | "reject" | "keep"; item: IdentityReview; customer?: Customer | null } | null;

export default function IdentityReviewPage() {
  const navigate = useNavigate();
  const qc = useQueryClient();
  const [sp, setSp] = useSearchParams();
  const { runId, run, runLoading, runError, refreshRun, processing, user, watchJob } = useWorkspace();
  const status = sp.get("status") || "REVIEW_REQUIRED";
  const [open, setOpen] = useState<IdentityReview | null>(null);
  const [pending, setPending] = useState<Pending>(null);
  const [customerSearch, setCustomerSearch] = useState("");
  const [alias, setAlias] = useState("");
  const [aliasCode, setAliasCode] = useState("");
  const [note, setNote] = useState("");
  const q = useQuery({ queryKey: ["identity", runId, "ALL"], queryFn: () => api.identityReviews(runId, "ALL"), enabled: !!runId && !processing });
  const customersQ = useQuery({ queryKey: ["customers", runId, customerSearch], queryFn: () => api.customers(runId as string, customerSearch), enabled: !!runId && !!open });
  const items = useMemo(() => (q.data?.items || []).filter((i) => status === "ALL" || i.status === status), [q.data, status]);
  const setStatus = (s: string) => setSp(s === "REVIEW_REQUIRED" ? {} : { status: s }, { replace: true });

  const after = (res: { message: string; job_id: string | null }) => { toast.success(res.message, { description: res.job_id ? "Re-running reconciliation with the updated identity decision…" : undefined }); qc.invalidateQueries({ queryKey: ["identity"] }); setOpen(null); setPending(null); setNote(""); if (res.job_id) watchJob(res.job_id); };
  const onError = (e: unknown) => toast.error(getErrorMessage(e, "The identity decision could not be saved."));
  const confirm = useMutation({ mutationFn: (p: { item: IdentityReview; code: string }) => api.identityConfirm({ run_id: runId as string, tan: p.item.tan, customer_code: p.code, reviewer: user.name, note: note || undefined }), onSuccess: after, onError });
  const reject = useMutation({ mutationFn: (p: { item: IdentityReview }) => api.identityReject({ run_id: runId as string, tan: p.item.tan, customer_code: p.item.suggested_customer_code || undefined, reviewer: user.name, note: note || undefined }), onSuccess: after, onError });
  const keep = useMutation({ mutationFn: (p: { item: IdentityReview }) => api.identityKeepUnmapped({ run_id: runId as string, tan: p.item.tan, reviewer: user.name, note: note || undefined }), onSuccess: after, onError });
  const addAlias = useMutation({ mutationFn: (p: { alias: string; code: string }) => api.identityAlias({ run_id: runId as string, alias: p.alias, customer_code: p.code, reviewer: user.name }), onSuccess: (res) => { after(res); setAlias(""); setAliasCode(""); }, onError });
  const busy = confirm.isPending || reject.isPending || keep.isPending || addAlias.isPending;
  const noRun = !runLoading && !runError && !runId;

  return <>
    <PageHeader eyebrow="IDENTITY RESOLUTION" title="Identity Review" subtitle="Resolve deductor TAN → customer mappings. Confirmed decisions are saved and reused in every future reconciliation for this assessee." />
    {runError && <ErrorNotice message="Reconciliation service is unavailable. Check the backend connection and try again." onRetry={refreshRun} />}
    {q.isError && <ErrorNotice message={getErrorMessage(q.error)} onRetry={() => q.refetch()} />}
    <div className="tab-bar" role="tablist" data-testid="identity-tabs">{TABS.map((t) => <button key={t} role="tab" aria-selected={status === t} className={`tab ${status === t ? "active" : ""}`} data-testid={`identity-tab-${t}`} onClick={() => setStatus(t)}>{t === "ALL" ? "All TANs" : IDENTITY_LABELS[t]}<em>{t === "ALL" ? Object.values(q.data?.counts || {}).reduce((a, b) => a + b, 0) : q.data?.counts?.[t] ?? 0}</em></button>)}</div>
    <section className="workspace-section table-section" data-testid="identity-table-section">
      <div className="table-toolbar"><div className="table-meta"><b data-testid="identity-count">{items.length} TAN{items.length === 1 ? "" : "s"}</b><span>REVIEW REQUIRED and UNMAPPED TANs keep their 26AS entries classified as IDENTITY_UNMAPPED until you decide.</span></div><button className="icon-button" data-testid="refresh-identity-button" aria-label="Refresh" onClick={() => q.refetch()}><RefreshCw size={15} className={q.isFetching ? "spin" : ""} /></button></div>
      {(runLoading || (q.isLoading && runId) || processing) ? <TableSkeleton cols={8} /> : noRun ? <EmptyState title="No reconciliation has been processed yet" text="Identity reviews appear after processing 26AS against the Customer Master." action={<button className="primary-button" data-testid="begin-workflow-button" onClick={() => navigate("/reconciliation/new")}><CloudUpload size={15} /> Begin workflow</button>} />
        : items.length === 0 ? <EmptyState icon={Check} title={status === "REVIEW_REQUIRED" ? "No identity reviews are pending" : `No ${IDENTITY_LABELS[status]?.toLowerCase() || ""} TANs`} text={status === "REVIEW_REQUIRED" ? "Every deductor TAN is resolved. Check the Unmapped tab for TANs without a suggestion." : "Switch tabs to see other identity states."} />
        : <div className="table-scroll"><table className="data-table" data-testid="identity-table"><thead><tr><th>TAN</th><th>Deductor</th><th>Status</th><th>Resolved / suggested Books Customer</th><th>Books Customer Code</th><th>Books Customer PAN</th><th className="num">Similarity</th><th className="num">Gap</th><th>Method</th><th className="num">26AS entries</th><th className="num">Tax deducted</th><th>History</th><th>Action</th></tr></thead>
          <tbody>{items.map((i) => <tr key={i.tan} data-testid={`identity-row-${i.tan}`}><td><b className="mono">{i.tan}</b></td><td><span className="ellipsis" title={i.deductor_name}>{i.deductor_name}</span>{i.other_names.length > 0 && <small className="muted"> +{i.other_names.length} variant</small>}</td><td><IdentityBadge value={i.status} /></td><td>{i.customer_name || i.suggested_customer_name || <i className="muted">No candidate</i>}</td><td className="mono">{i.customer_code || i.suggested_customer_code || "—"}</td><td className="mono">{maskPan(i.customer_pan)}</td><td className="num">{i.method === "FUZZY" || i.status !== "EXACT" ? pct(i.score * 100, 0) : "100%"}</td><td className="num">{i.status === "EXACT" ? "—" : pct(i.confidence_gap * 100, 0)}</td><td>{IDENTITY_METHOD_LABELS[i.method] || i.method}</td><td className="num">{i.transaction_count}</td><td className="num"><Amount value={i.total_tax_deducted} /></td><td>{i.historical_mapping ? <span className="badge blue" title={`Confirmed by ${i.historical_mapping.reviewer}`}><History size={11} /> saved</span> : i.decision ? <span className="badge muted">{i.decision.action === "KEEP_UNMAPPED" ? "kept unmapped" : "rejected"}</span> : "—"}</td><td className="actions"><button className="mini-button" data-testid={`review-identity-${i.tan}`} onClick={() => { setOpen(i); setCustomerSearch(""); }}>{i.status === "EXACT" ? "View" : "Review"}</button></td></tr>)}</tbody></table></div>}
    </section>

    <Drawer open={!!open} onClose={() => setOpen(null)} title={open ? <span className="mono">{open.tan}</span> : ""} subtitle={open?.deductor_name} width={760} testId="identity-drawer">
      {open && <div className="identity-detail">
        <div className="detail-badges"><IdentityBadge value={open.status} /><span className="badge outline">{IDENTITY_METHOD_LABELS[open.method] || open.method}</span><span className="badge muted">{open.transaction_count} entries · {inr(open.total_tax_deducted)}</span><span className="badge muted">{open.quarters.join(", ")}</span></div>
        <div className="detail-kpis"><div><span>SIMILARITY SCORE</span><b data-testid="identity-score">{pct(open.score * 100, 0)}</b></div><div><span>CONFIDENCE</span><b>{pct(open.confidence * 100, 0)}</b></div><div><span>CONFIDENCE GAP</span><b>{pct(open.confidence_gap * 100, 0)}</b><small>to next candidate</small></div><div><span>RESOLUTION</span><b>{IDENTITY_LABELS[open.status]}</b><small>{open.status === "REVIEW_REQUIRED" ? "not used for matching" : open.status === "UNMAPPED" ? "no candidate" : "used for matching"}</small></div></div>
        <section className="detail-section"><span className="eyebrow">MATCH SIGNALS</span><ul className="signal-list" data-testid="identity-signals">{open.signals.map((s, i) => <li key={i}>{s}</li>)}</ul>{open.other_names.length > 0 && <p className="muted-copy">Other names on this TAN: {open.other_names.join("; ")}</p>}</section>
        {(open.historical_mapping || open.decision) && <section className="detail-section" data-testid="identity-provenance"><span className="eyebrow">AUDIT / PROVENANCE</span><div className="detail-fields compact">{open.historical_mapping && <><div className="field"><span>Reviewer</span><b>{open.historical_mapping.reviewer}</b></div><div className="field"><span>Timestamp</span><b>{fmtDateTime(open.historical_mapping.timestamp)}</b></div><div className="field"><span>Resolution method</span><b>{open.historical_mapping.method}</b></div><div className="field"><span>Source</span><b>{open.historical_mapping.source}</b></div><div className="field"><span>Mapped to</span><b>{open.historical_mapping.customer_code} · {open.historical_mapping.customer_name}</b></div>{open.historical_mapping.previous && <div className="field"><span>Previous decision</span><b>{open.historical_mapping.previous.customer_code} by {open.historical_mapping.previous.reviewer} ({fmtDateTime(open.historical_mapping.previous.timestamp)})</b></div>}</>}{open.decision && <><div className="field"><span>Decision</span><b>{open.decision.action.replaceAll("_", " ")}</b></div><div className="field"><span>Reviewer</span><b>{open.decision.reviewer}</b></div><div className="field"><span>Timestamp</span><b>{fmtDateTime(open.decision.timestamp)}</b></div>{open.decision.rejected_codes.length > 0 && <div className="field"><span>Rejected candidates</span><b className="mono">{open.decision.rejected_codes.join(", ")}</b></div>}</>}</div></section>}
        <section className="detail-section"><span className="eyebrow">CANDIDATE CUSTOMERS</span>{open.candidates.length ? <table className="mini-table" data-testid="identity-candidates"><thead><tr><th>Code</th><th>Customer</th><th>PAN</th><th className="num">Similarity</th><th /></tr></thead><tbody>{open.candidates.map((c) => <tr key={c.customer_code} className={c.customer_code === (open.customer_code || open.suggested_customer_code) ? "current" : ""}><td className="mono">{c.customer_code}</td><td>{c.customer_name}</td><td className="mono">{maskPan(c.customer_pan)}</td><td className="num">{pct(c.score * 100, 0)}</td><td className="actions">{open.status !== "EXACT" && <button className="mini-button green" data-testid={`confirm-candidate-${c.customer_code}`} onClick={() => setPending({ kind: "confirm", item: open, customer: { customer_code: c.customer_code, customer_name: c.customer_name, pan: c.customer_pan, gstin: c.customer_gstin, tans: [], source: "" } })}><Check size={12} /> Confirm</button>}</td></tr>)}</tbody></table> : <p className="muted-copy">No fuzzy candidates — resolved directly from trusted data.</p>}</section>
        {open.status !== "EXACT" && <section className="detail-section"><span className="eyebrow">SEARCH CUSTOMER</span><div className="search-field"><Search size={14} /><input data-testid="customer-search-input" placeholder="Search by code, name, PAN or TAN…" value={customerSearch} onChange={(e) => setCustomerSearch(e.target.value)} /></div>{customersQ.isLoading ? <p className="muted-copy">Loading customers…</p> : customersQ.data?.length ? <ul className="customer-results" data-testid="customer-results">{customersQ.data.slice(0, 8).map((c) => <li key={c.customer_code}><div><b className="mono">{c.customer_code}</b> {c.customer_name}<small>{maskPan(c.pan)}{c.tans.length ? ` · TANs: ${c.tans.join(", ")}` : ""}</small></div><button className="mini-button green" data-testid={`map-customer-${c.customer_code}`} onClick={() => setPending({ kind: "confirm", item: open, customer: c })}><Check size={12} /> Map</button></li>)}</ul> : <p className="muted-copy">No customers match.</p>}</section>}
        <section className="detail-section"><span className="eyebrow">ADD ALIAS</span><p className="muted-copy">Save an alternate name so this deductor name resolves automatically in future runs.</p><div className="note-form inline"><input data-testid="alias-input" placeholder="Alias (defaults to deductor name)" value={alias || open.deductor_name} onChange={(e) => setAlias(e.target.value)} /><input data-testid="alias-customer-input" className="mono" placeholder="Customer code" value={aliasCode || open.customer_code || open.suggested_customer_code || ""} onChange={(e) => setAliasCode(e.target.value.toUpperCase())} /><button className="secondary-button" data-testid="add-alias-button" disabled={busy || !(aliasCode || open.customer_code || open.suggested_customer_code)} onClick={() => addAlias.mutate({ alias: alias || open.deductor_name, code: aliasCode || open.customer_code || open.suggested_customer_code || "" })}><Tag size={13} /> Save alias</button></div></section>
        <section className="detail-section"><span className="eyebrow">REVIEW NOTE (OPTIONAL)</span><textarea data-testid="identity-note-input" rows={2} placeholder="Evidence used for this decision…" value={note} onChange={(e) => setNote(e.target.value)} /></section>
        {open.status !== "EXACT" && <div className="wizard-actions identity-actions" data-testid="identity-actions"><button className="secondary-button" data-testid="keep-unmapped-button" disabled={busy} onClick={() => setPending({ kind: "keep", item: open })}><ShieldOff size={14} /> Keep unmapped</button>{open.suggested_customer_code && <button className="secondary-button danger" data-testid="reject-mapping-button" disabled={busy} onClick={() => setPending({ kind: "reject", item: open })}><X size={14} /> Reject suggestion</button>}{(open.suggested_customer_code || open.customer_code) && <button className="primary-button" data-testid="confirm-mapping-button" disabled={busy} onClick={() => setPending({ kind: "confirm", item: open, customer: null })}><Check size={14} /> Confirm mapping → {open.customer_code || open.suggested_customer_code}</button>}</div>}
      </div>}
    </Drawer>

    <ConfirmDialog open={!!pending} testId="identity-confirm-dialog" busy={busy} danger={pending?.kind !== "confirm"} onCancel={() => setPending(null)}
      title={pending?.kind === "confirm" ? "Confirm identity mapping" : pending?.kind === "reject" ? "Reject suggested customer" : "Keep TAN unmapped"}
      confirmLabel={pending?.kind === "confirm" ? "Confirm & save" : pending?.kind === "reject" ? "Reject" : "Keep unmapped"}
      description={<>{pending?.kind === "confirm" && <>Map TAN <b className="mono">{pending.item.tan}</b> ({pending.item.deductor_name}) to customer <b>{pending.customer?.customer_code || pending.item.customer_code || pending.item.suggested_customer_code} · {pending.customer?.customer_name || pending.item.customer_name || pending.item.suggested_customer_name}</b>. This mapping will be saved for future reconciliations of assessee {run?.assessee_pan ? maskPan(run.assessee_pan) : "(no PAN)"} and matching will re-run now.</>}{pending?.kind === "reject" && <>The suggestion <b>{pending.item.suggested_customer_code}</b> will not be proposed again for TAN <b className="mono">{pending.item.tan}</b>. Its 26AS entries stay IDENTITY_UNMAPPED until mapped.</>}{pending?.kind === "keep" && <>TAN <b className="mono">{pending.item.tan}</b> will remain unmapped. Its {pending.item.transaction_count} 26AS entr{pending.item.transaction_count === 1 ? "y" : "ies"} ({inr(pending.item.total_tax_deducted)}) stay classified as IDENTITY_UNMAPPED and are reported as exceptions.</>}</>}
      onConfirm={() => { if (!pending) return; if (pending.kind === "confirm") confirm.mutate({ item: pending.item, code: pending.customer?.customer_code || pending.item.customer_code || pending.item.suggested_customer_code || "" }); else if (pending.kind === "reject") reject.mutate({ item: pending.item }); else keep.mutate({ item: pending.item }); }} />
  </>;
}
