import { useState } from "react";
import { useNavigate } from "react-router-dom";
import { useQuery, useQueryClient } from "@tanstack/react-query";
import { CloudUpload, Download, FileCheck2, FileSpreadsheet, FileText, FileType2, Loader2 } from "lucide-react";
import { toast } from "sonner";
import { EmptyState, ErrorNotice, PageHeader } from "../components/common";
import { useWorkspace } from "../context/WorkspaceContext";
import { fmtDateTime } from "../lib/format";
import { api, getErrorMessage } from "../services/api";

const DESCRIPTIONS: Record<string, string> = { ca_reconciliation: "Every result row with match method, claimability, reason and recommended action — the primary working paper.", exceptions: "All non-claimable outcomes with severity, review status and CA notes.", control_totals: "Books vs 26AS totals, matched amounts, differences, coverage and outcome counts.", party_followup: "Customer-wise list of short deductions, missing credits and unfiled statements to chase.", customer_summary: "Per-customer books TDS, 26AS TDS, difference and outcome counts.", tan_summary: "Per-deductor TAN entries, amounts deducted/deposited and identity status.", quarterly_summary: "Quarter-wise books vs 26AS TDS with matched and exception counts." };
const FORMAT_ICON: Record<string, React.ElementType> = { xlsx: FileSpreadsheet, csv: FileType2, pdf: FileText };

export default function ReportsPage() {
  const navigate = useNavigate();
  const qc = useQueryClient();
  const { runId, run, runLoading, runError, refreshRun } = useWorkspace();
  const q = useQuery({ queryKey: ["reports", runId], queryFn: () => api.reportsAvailable(runId), enabled: !!runId });
  const history = useQuery({ queryKey: ["report-history", runId], queryFn: () => api.reportHistory(runId), enabled: !!runId });
  const [busy, setBusy] = useState<string | null>(null);
  const available = run?.status === "COMPLETED";
  const download = async (report: string, format: string) => {
    setBusy(`${report}:${format}`);
    try { const name = await api.downloadReport(report, format, runId); toast.success("Report downloaded", { description: name }); qc.invalidateQueries({ queryKey: ["report-history"] }); }
    catch (e) { toast.error(getErrorMessage(e, "Report generation failed. Try again.")); }
    finally { setBusy(null); }
  };
  const noRun = !runLoading && !runError && !runId;
  return <>
    <PageHeader eyebrow="OUTPUTS" title="Reports" subtitle={run ? `Generated from the ${run.source === "sample" ? "sample " : ""}run for ${run.assessee_name || "unnamed assessee"} · FY ${run.financial_year || "—"}` : "Audit-ready outputs generated by the reconciliation engine from the selected run."} />
    {runError && <ErrorNotice message="Reconciliation service is unavailable. Check the backend connection and try again." onRetry={refreshRun} />}
    {q.isError && <ErrorNotice message={getErrorMessage(q.error)} onRetry={() => q.refetch()} />}
    {noRun ? <section className="workspace-section"><EmptyState title="No reports have been generated" text="Reports are generated from a completed reconciliation run. Process Books and 26AS first." action={<button className="primary-button" data-testid="begin-workflow-button" onClick={() => navigate("/reconciliation/new")}><CloudUpload size={15} /> Begin workflow</button>} /></section>
      : <>
        {run && !available && <ErrorNotice testId="reports-unavailable" message={run.status === "PROCESSING" ? "The selected run is still processing. Reports become available when it completes." : "The selected run failed, so no reports can be generated from it."} />}
        <div className="report-grid" data-testid="report-grid">{(q.data?.reports || Object.keys(DESCRIPTIONS).map((k) => ({ key: k, label: k, available: false }))).map((r) => <article className={`report-card ${available ? "" : "disabled"}`} key={r.key} data-testid={`report-card-${r.key}`}><div className="report-icon"><FileCheck2 size={17} /></div><h3>{r.label}</h3><p>{DESCRIPTIONS[r.key]}</p><div className="format-buttons">{(q.data?.formats || ["xlsx", "csv", "pdf"]).map((f) => { const Icon = FORMAT_ICON[f]; const id = `${r.key}:${f}`; return <button key={f} className="secondary-button" data-testid={`download-${r.key}-${f}`} disabled={!available || !!busy} onClick={() => download(r.key, f)}>{busy === id ? <Loader2 size={13} className="spin" /> : <Icon size={13} />} {f.toUpperCase()}</button>; })}</div></article>)}</div>
        <section className="workspace-section" data-testid="report-history"><div className="section-heading"><div><span className="eyebrow">AUDIT TRAIL</span><h2>Generated reports</h2></div></div>{history.data?.length ? <table className="mini-table"><thead><tr><th>Report</th><th>Format</th><th className="num">Rows</th><th>Generated</th><th>File</th></tr></thead><tbody>{history.data.map((h, i) => <tr key={i}><td>{q.data?.reports.find((r) => r.key === h.report)?.label || h.report}</td><td className="mono">{h.format.toUpperCase()}</td><td className="num">{h.rows}</td><td>{fmtDateTime(h.generated_at)}</td><td className="mono ellipsis" title={h.filename}><Download size={11} /> {h.filename}</td></tr>)}</tbody></table> : <EmptyState title="No reports have been generated yet" text="Downloads from this run will be logged here." testId="report-history-empty" />}</section>
      </>}
  </>;
}
