import { useMemo, useState } from "react";
import { useMutation, useQuery, useQueryClient } from "@tanstack/react-query";
import { Navigate, useNavigate, useParams } from "react-router-dom";
import { AlertTriangle, ArrowRight, Check, Circle, FileCheck2, LockKeyhole, PlayCircle, ShieldCheck } from "lucide-react";
import { ErrorNotice, InfoNotice, PageHeader } from "../components/common";
import { api, getErrorMessage } from "../services/api";
import type { TdsComplianceAssignment, TdsComplianceWorkspace } from "../types";

type PlanState = "NOT_STARTED" | "WAITING_FOR_INPUT" | "READY_FOR_REVIEW" | "COMPLETED" | "COMPLETED_WITH_EXCEPTIONS" | "BLOCKED" | "LOCKED";
type PlanStep = { key: string; name: string; purpose: string; state: PlanState; completed: string; next: string; path: string; action: string };
const stateLabel: Record<PlanState, string> = { NOT_STARTED: "Not Started", WAITING_FOR_INPUT: "Waiting for Input", READY_FOR_REVIEW: "Ready for Review", COMPLETED: "Completed", COMPLETED_WITH_EXCEPTIONS: "Completed - Review Required", BLOCKED: "Blocked", LOCKED: "Locked" };
const tone = (state: PlanState) => state === "COMPLETED" || state === "LOCKED" ? "green" : state === "COMPLETED_WITH_EXCEPTIONS" || state === "READY_FOR_REVIEW" ? "amber" : state === "BLOCKED" ? "red" : "slate";
const hasSource = (workspace: TdsComplianceWorkspace, fragment: string) => workspace.sources.some(source => source.key.toLowerCase().includes(fragment) && source.committed);

export function resolveAssignmentPlan(workspace: TdsComplianceWorkspace, data: { returnArtifacts: number; returnExceptions: number; transactionReviews: number; interestRuns: number }) {
  const { assignment, overview, runs } = workspace;
  const locked = assignment.status === "LOCKED" || overview.lock_status === "LOCKED";
  const setupComplete = Boolean(assignment.organization_id && assignment.client_id && assignment.assessee_legal_name && assignment.financial_year);
  const ledgerReady = Boolean(runs.ledger_version_id) || hasSource(workspace, "ledger");
  const calculationReady = Boolean(runs.calculation_id) || overview.transactions_calculated > 0;
  const depositEvidenceReady = hasSource(workspace, "deposit");
  const depositReady = Boolean(runs.deposit_run_id);
  const interestReady = data.interestRuns > 0 || Boolean(runs.interest_run_id);
  const returnReady = data.returnArtifacts > 0;
  const openReviews = data.transactionReviews + data.returnExceptions + (overview.deposit_issues || 0) + (overview.interest_issues || 0);
  const hold = (state: PlanState) => locked ? "LOCKED" : state;
  const steps: PlanStep[] = [
    { key: "setup", name: "Assignment Setup", purpose: "Confirm the client and reporting period that controls this assignment.", state: hold(setupComplete ? "COMPLETED" : "BLOCKED"), completed: setupComplete ? "Client and period information recorded" : "Mandatory assignment information is incomplete", next: setupComplete ? "Continue to the payment ledger" : "Complete the assignment details", path: "/tds-compliance/assignments", action: "Open Assignments" },
    { key: "ledger", name: "Payment Ledger", purpose: "Load and validate the company payment ledger used for TDS calculations.", state: hold(ledgerReady ? "COMPLETED" : "WAITING_FOR_INPUT"), completed: ledgerReady ? `${overview.transactions_uploaded || 0} committed ledger transaction${overview.transactions_uploaded === 1 ? "" : "s"}` : "No committed payment ledger", next: ledgerReady ? "Calculation is available" : "Upload, validate and commit the payment ledger", path: "/tds-compliance/ledger", action: ledgerReady ? "Open Ledger" : "Upload Payment Ledger" },
    { key: "calculation", name: "TDS Calculation", purpose: "Apply the existing approved rules to the committed ledger.", state: hold(!ledgerReady ? "BLOCKED" : !calculationReady ? "READY_FOR_REVIEW" : overview.exceptions ? "COMPLETED_WITH_EXCEPTIONS" : "COMPLETED"), completed: calculationReady ? `${overview.transactions_calculated || 0} transaction${overview.transactions_calculated === 1 ? "" : "s"} calculated` : "No persisted calculation yet", next: !ledgerReady ? "Commit a payment ledger first" : !calculationReady ? "Review and run the existing calculation" : overview.exceptions ? "Review calculation exceptions" : "Continue to deposit evidence", path: "/tds-compliance/calculation", action: calculationReady ? "Review Calculations" : "Open Calculation" },
    { key: "deposit", name: "Deposit & Challans", purpose: "Review deposit evidence and challan relationships against calculated liability.", state: hold(!calculationReady ? "BLOCKED" : !depositEvidenceReady ? "WAITING_FOR_INPUT" : !depositReady ? "READY_FOR_REVIEW" : overview.deposit_issues ? "COMPLETED_WITH_EXCEPTIONS" : "COMPLETED"), completed: !depositEvidenceReady ? "No deposit evidence has been provided" : depositReady ? "Deposit review result is persisted" : "Deposit evidence is committed", next: !calculationReady ? "Complete the calculation first" : !depositEvidenceReady ? "Upload deposit evidence" : !depositReady ? "Review deposit evidence and relationships" : overview.deposit_issues ? `${overview.deposit_issues} item(s) need review` : "Deposit evidence has no current exceptions", path: "/tds-compliance/deposit", action: depositEvidenceReady ? "Review Deposit" : "Upload Deposit Evidence" },
    { key: "interest", name: "Interest & Delay", purpose: "Review the existing persisted timing and interest results.", state: hold(!depositReady ? "BLOCKED" : !interestReady ? "WAITING_FOR_INPUT" : overview.interest_issues ? "COMPLETED_WITH_EXCEPTIONS" : "COMPLETED"), completed: interestReady ? "Persisted interest review is available" : "No persisted interest review", next: !depositReady ? "Commit deposit evidence first" : !interestReady ? "Run the existing interest workflow" : overview.interest_issues ? `${overview.interest_issues} timing item(s) need review` : "Continue to return audit", path: "/tds-compliance/interest", action: interestReady ? "Review Interest" : "Open Interest" },
    { key: "return", name: "Return Audit", purpose: "Compare the quarterly filing artifact with the controlled assignment evidence.", state: hold(!returnReady ? "WAITING_FOR_INPUT" : data.returnExceptions ? "COMPLETED_WITH_EXCEPTIONS" : "COMPLETED"), completed: returnReady ? `${data.returnArtifacts} return artifact${data.returnArtifacts === 1 ? "" : "s"} received` : "No quarterly return artifact", next: !returnReady ? "Upload the quarterly TDS return artifact" : data.returnExceptions ? `${data.returnExceptions} return item(s) need review` : "Return audit has no current exceptions", path: "/tds-compliance/return-audit", action: returnReady ? "Review Return Audit" : "Upload Return" },
    { key: "reviews", name: "Review Queue", purpose: "Bring unresolved calculation, evidence, interest and return items into one CA review list.", state: hold(openReviews ? "READY_FOR_REVIEW" : "COMPLETED"), completed: openReviews ? `${openReviews} open review item${openReviews === 1 ? "" : "s"}` : "No open review items", next: openReviews ? "Resolve the next review item" : "No CA decision is currently pending", path: "/tds-compliance/review-queue", action: openReviews ? "Review Items" : "Open Review Queue" },
    { key: "reports", name: "Reports", purpose: "See the report types that are available for this assignment.", state: hold("NOT_STARTED"), completed: "Report availability is shown without unsupported exports", next: "Review available reports", path: "/tds-compliance/reports", action: "Open Reports" },
    { key: "lock", name: "Final Review & Lock", purpose: "Perform the final CA-controlled readiness review before preserving the assignment state.", state: locked ? "LOCKED" : setupComplete && ledgerReady && calculationReady && depositReady && interestReady && returnReady && !openReviews ? "READY_FOR_REVIEW" : "BLOCKED", completed: locked ? "Assignment is locked" : "Final review remains CA-controlled", next: locked ? "No operational changes are available" : openReviews ? `${openReviews} open review item(s) must be addressed` : "Confirm final review and lock the assignment", path: "#final-review", action: locked ? "Locked" : "Final Review" },
  ];
  const current = steps.find(step => !["COMPLETED", "LOCKED", "NOT_STARTED"].includes(step.state)) || steps[steps.length - 1];
  return { steps, current, openReviews, readyToLock: !locked && current.key === "lock" && current.state === "READY_FOR_REVIEW" };
}

export function TdsPlanLandingPage() {
  const assignments = useQuery({ queryKey: ["tds-compliance-assignments"], queryFn: api.tdsComplianceAssignments });
  if (assignments.isLoading) return <main className="page"><PageHeader eyebrow="TDS COMPLIANCE" title="Assignment Plan" subtitle="Loading the most recent assignment." /><InfoNotice>Loading assignments...</InfoNotice></main>;
  if (assignments.isError) return <main className="page"><PageHeader eyebrow="TDS COMPLIANCE" title="Assignment Plan" subtitle="Select an assignment to continue." /><ErrorNotice message="Assignments could not be loaded." /></main>;
  if (!assignments.data?.length) return <main className="page"><PageHeader eyebrow="TDS COMPLIANCE" title="Assignment Plan" subtitle="Create an assignment before opening a compliance plan." /><InfoNotice>Create an assignment to begin the guided compliance plan.</InfoNotice></main>;
  return <Navigate replace to={`/tds-compliance/assignments/${encodeURIComponent(assignments.data[0].assignment_id)}/plan`} />;
}

export default function TdsAssignmentPlanPage() {
  const { assignmentId = "" } = useParams(); const navigate = useNavigate(); const queryClient = useQueryClient(); const [confirming, setConfirming] = useState(false);
  const workspace = useQuery({ queryKey: ["tds-compliance-workspace", assignmentId], queryFn: () => api.tdsComplianceWorkspace(assignmentId), enabled: Boolean(assignmentId) });
  const transactions = useQuery({ queryKey: ["tds-transactions", assignmentId], queryFn: () => api.tdsComplianceTransactions(assignmentId), enabled: Boolean(assignmentId) });
  const artifacts = useQuery({ queryKey: ["return-artifacts", assignmentId], queryFn: () => api.returnAuditArtifacts(assignmentId), enabled: Boolean(assignmentId) });
  const returns = useQuery({ queryKey: ["return-audit-results", assignmentId], queryFn: () => api.returnAuditResults(assignmentId), enabled: Boolean(assignmentId) });
  const interest = useQuery({ queryKey: ["persisted-interest", assignmentId], queryFn: () => api.persistedInterestCompliance(assignmentId), enabled: Boolean(assignmentId) });
  const lock = useMutation({ mutationFn: () => api.lockTdsComplianceAssignment(assignmentId), onSuccess: () => { setConfirming(false); void queryClient.invalidateQueries({ queryKey: ["tds-compliance-workspace", assignmentId] }); void queryClient.invalidateQueries({ queryKey: ["tds-compliance-assignments"] }); } });
  const plan = useMemo(() => workspace.data ? resolveAssignmentPlan(workspace.data, { returnArtifacts: artifacts.data?.length || 0, returnExceptions: (returns.data || []).filter(item => item.status !== "MATCHED").length, transactionReviews: (transactions.data?.items || []).filter(item => item.transaction_status?.includes("REVIEW") || item.calculation_status === "REVIEW_REQUIRED").length, interestRuns: interest.data?.length || 0 }) : null, [workspace.data, artifacts.data, returns.data, transactions.data, interest.data]);
  if (workspace.isLoading) return <main className="page"><PageHeader eyebrow="TDS COMPLIANCE PLAN" title="Loading assignment plan" subtitle="Loading persisted assignment evidence and workflow status." /><InfoNotice>Loading assignment plan...</InfoNotice></main>;
  if (workspace.isError || !workspace.data) return <main className="page"><PageHeader eyebrow="TDS COMPLIANCE PLAN" title="Assignment plan" subtitle="The selected assignment could not be loaded." /><ErrorNotice message={getErrorMessage(workspace.error, "Assignment plan could not be loaded.")} /></main>;
  const { assignment, overview } = workspace.data; const current = plan!.current;
  const go = (path: string) => path.startsWith("#") ? document.getElementById(path.slice(1))?.scrollIntoView({ behavior: "smooth" }) : navigate(`${path}?assignment=${encodeURIComponent(assignmentId)}`);
  return <main className="page"><PageHeader eyebrow="TDS COMPLIANCE" title="Assignment Plan" subtitle="A guided, evidence-led compliance plan for this client and reporting period." action={<button className="primary-button" onClick={() => go(current.path)}>Continue Assignment <ArrowRight size={15} /></button>} />
    <section className="plan-context"><div><span>CLIENT</span><b>{assignment.assessee_legal_name}</b></div><div><span>PAN</span><b>{assignment.assessee_pan || "Not provided"}</b></div><div><span>TAN</span><b>{assignment.tan || "Not provided"}</b></div><div><span>FY / QUARTER</span><b>{assignment.financial_year} / {assignment.quarter || "All quarters"}</b></div><div><span>ASSIGNMENT STATUS</span><b>{assignment.status.replaceAll("_", " ")}</b></div><div><span>LAST ACTIVITY</span><b>{overview.last_updated ? new Date(overview.last_updated).toLocaleString() : "Not recorded"}</b></div></section>
    <section className="plan-current"><div><span className="eyebrow">CURRENT STEP</span><h2>Step {plan!.steps.indexOf(current) + 1} of 9 - {current.name}</h2><p>{current.next}</p></div><button className="primary-button" onClick={() => go(current.path)}>{current.action} <ArrowRight size={15} /></button></section>
    <section className="plan-layout"><ol className="plan-timeline">{plan!.steps.map((step, index) => <li key={step.key} className={step.key === current.key ? "current" : ""}><div className={"plan-icon " + tone(step.state)}>{step.state === "COMPLETED" || step.state === "LOCKED" ? <Check size={16} /> : step.state === "BLOCKED" || step.state === "COMPLETED_WITH_EXCEPTIONS" ? <AlertTriangle size={16} /> : <Circle size={16} />}</div><div><b>{index + 1}. {step.name}</b><small>{stateLabel[step.state]}</small></div></li>)}</ol>
      <div className="plan-cards">{plan!.steps.map((step, index) => <article className={"plan-step-card " + (step.key === current.key ? "current" : "")} key={step.key} id={step.key === "lock" ? "final-review" : undefined}><div className="plan-step-heading"><div><span className="eyebrow">STEP {index + 1}</span><h2>{step.name}</h2></div><span className={"badge " + tone(step.state)}>{stateLabel[step.state]}</span></div><dl><dt>Why it is needed</dt><dd>{step.purpose}</dd><dt>Completed</dt><dd>{step.completed}</dd><dt>Required next</dt><dd>{step.next}</dd></dl>{step.key === "lock" && plan!.readyToLock ? <button className="primary-button" onClick={() => setConfirming(true)}><LockKeyhole size={15} />Lock Assignment</button> : <button className="secondary-button" disabled={step.state === "LOCKED"} onClick={() => go(step.path)}>{step.action} {step.key !== "lock" && <ArrowRight size={14} />}</button>}</article>)}</div></section>
    <section className="workspace-section plan-review-summary"><div><span className="eyebrow">FINAL READINESS</span><h2>{plan!.readyToLock ? "Ready for CA lock" : assignment.status === "LOCKED" ? "Assignment locked" : "Not ready to lock"}</h2><p>Open review items: <b>{plan!.openReviews}</b>. Locking is always a CA-controlled action.</p>{!plan!.readyToLock && assignment.status !== "LOCKED" && <button className="secondary-button" onClick={() => go("/tds-compliance/review-queue")}>Review Outstanding Items</button>}</div><FileCheck2 size={24} /></section>
    {confirming && <div className="plan-modal-backdrop" role="presentation"><section className="plan-modal" role="dialog" aria-modal="true" aria-labelledby="lock-title"><span className="eyebrow">FINAL CA ACTION</span><h2 id="lock-title">Lock this assignment?</h2><p>Locking preserves the final audit state and prevents further operational changes according to the assignment rules.</p>{lock.isError && <ErrorNotice message={getErrorMessage(lock.error, "The assignment could not be locked.")} />}<div><button className="secondary-button" onClick={() => setConfirming(false)} disabled={lock.isPending}>Cancel</button><button className="primary-button" onClick={() => lock.mutate()} disabled={lock.isPending}>{lock.isPending ? "Locking..." : "Lock Assignment"}</button></div></section></div>}
  </main>;
}
