import { useMemo, useState } from "react";
import { useMutation, useQuery, useQueryClient } from "@tanstack/react-query";
import { ArrowLeft, CheckCircle2, ClipboardCheck, FileClock, Plus, ShieldCheck } from "lucide-react";
import { PageHeader } from "../components/common";
import { useWorkspace } from "../context/WorkspaceContext";
import { api, getErrorMessage } from "../services/api";
import type { TdsComplianceRule, TdsComplianceRuleDraft } from "../types";

const blank = (organizationId: string, clientId?: string): TdsComplianceRuleDraft => ({ organization_id: organizationId, scope: clientId ? "CLIENT" : "ORGANIZATION", client_id: clientId || null, assignment_id: null, financial_year: "", effective_from: "", effective_to: "", governing_act: "", payment_nature: "", deductee_type: "", section_reference: "", historical_section_reference: null, table_reference: null, rate: "", no_pan_rate: null, threshold: "", threshold_type: "NO_THRESHOLD", per_transaction_threshold: "", aggregate_financial_year_threshold: "", excess_only: false, calculation_basis: "full_amount", rule_defined_base_field: null, rounding_method: "HALF_UP", rounding_precision: 2, priority: 0, source: "", source_reference: "" });
const pretty = (value?: string | null) => value === "DEACTIVATED" ? "Inactive" : value ? value.replaceAll("_", " ") : "Not specified";
const stepTitles = ["Rule identity", "Applicability", "Calculation", "Source & governance", "Review"];

export default function TdsComplianceSettingsPage() {
  const { clientId } = useWorkspace(); const queryClient = useQueryClient();
  const rulesQuery = useQuery({ queryKey: ["tds-compliance-rules"], queryFn: api.tdsComplianceRules });
  const [creating, setCreating] = useState(false); const [step, setStep] = useState(0); const [draft, setDraft] = useState(() => blank("TEST_ORG", clientId)); const [editingId, setEditingId] = useState<string | null>(null); const [selected, setSelected] = useState<TdsComplianceRule | null>(null); const [notice, setNotice] = useState<string | null>(null);
  const [filters, setFilters] = useState({ fy: "", law: "", nature: "", type: "", status: "", search: "" });
  const refresh = () => queryClient.invalidateQueries({ queryKey: ["tds-compliance-rules"] });
  const save = useMutation({ mutationFn: () => editingId ? api.updateTdsComplianceRule(editingId, draft) : api.createTdsComplianceRule(draft), onSuccess: (rule) => { setCreating(false); setEditingId(null); setSelected(rule); setNotice(`Draft ${rule.rule_id} saved. Submit it for approval when the statutory source has been reviewed.`); refresh(); }, onError: (error) => setNotice(getErrorMessage(error)) });
  const action = useMutation({ mutationFn: ({ rule, kind }: { rule: TdsComplianceRule; kind: "submit" | "approve" | "activate" | "deactivate" }) => kind === "submit" ? api.submitTdsComplianceRule(rule.rule_id) : kind === "approve" ? api.approveTdsComplianceRule(rule.rule_id) : kind === "activate" ? api.activateTdsComplianceRule(rule.rule_id) : api.deactivateTdsComplianceRule(rule.rule_id), onSuccess: (rule) => { setSelected(rule); setNotice(`${rule.rule_id} is now ${pretty(rule.lifecycle).toLowerCase()}.`); refresh(); }, onError: (error) => setNotice(getErrorMessage(error)) });
  const set = (key: keyof TdsComplianceRuleDraft, value: unknown) => setDraft((current) => ({ ...current, [key]: value }));
  const rules = useMemo(() => (rulesQuery.data || []).filter((rule) => (!filters.fy || rule.financial_year === filters.fy) && (!filters.law || rule.governing_act === filters.law) && (!filters.nature || rule.payment_nature === filters.nature) && (!filters.type || rule.deductee_type === filters.type) && (!filters.status || rule.lifecycle === filters.status) && (!filters.search || `${rule.section_reference} ${rule.payment_nature}`.toLowerCase().includes(filters.search.toLowerCase()))), [rulesQuery.data, filters]);
  const values = (key: keyof TdsComplianceRule) => Array.from(new Set((rulesQuery.data || []).map((rule) => String(rule[key] || "")).filter(Boolean)));
  const start = () => { setDraft(blank("TEST_ORG", clientId)); setEditingId(null); setStep(0); setCreating(true); setSelected(null); setNotice(null); };
  const version = (rule: TdsComplianceRule) => { const { rule_id, rule_family_id, rule_version, version: oldVersion, lifecycle, active, updated_at, ...rest } = rule; void rule_id; void rule_family_id; void rule_version; void oldVersion; void lifecycle; void active; void updated_at; setDraft(rest); setEditingId(null); setStep(0); setCreating(true); setSelected(null); };
  const editDraft = (rule: TdsComplianceRule) => { const { rule_id, rule_family_id, rule_version, version: oldVersion, lifecycle, active, updated_at, ...rest } = rule; void rule_family_id; void rule_version; void oldVersion; void lifecycle; void active; void updated_at; setDraft(rest); setEditingId(rule_id); setStep(0); setCreating(true); setSelected(null); };
  return <><PageHeader eyebrow="TDS COMPLIANCE · RULE GOVERNANCE" title="TDS Statutory Rule Library" subtitle="Review the controlled rules used for deductor-side TDS calculations. Each rule shows its applicability, calculation parameters, source period and lifecycle status." />
    {notice && <div className="notice info">{notice}</div>}
    {!creating && <section className="workspace-section tds-rule-library"><div className="section-heading"><div><span className="eyebrow">CONTROLLED RULE REGISTER</span><h2><ShieldCheck size={16} /> Statutory configurations</h2><p className="muted">Use filters to locate a rule. Open a rule to review its source, version history and governance trail before changing its status.</p></div><button className="btn primary" onClick={start}><Plus size={16} /> Add statutory rule</button></div>
      {!rulesQuery.isLoading && !rulesQuery.data?.length ? <div className="empty-state"><ShieldCheck size={30} /><h3>No statutory rules configured for this scope</h3><p>Configure rules using your CA-approved statutory rule source before running automated TDS calculations.</p><div className="button-row"><button className="btn primary" onClick={start}>Add statutory rule</button><button className="btn secondary" onClick={() => setNotice("Select a rule to view its governance audit trail.")}>View audit trail</button></div></div> : <><div className="form-grid compact"><Filter label="Financial year" value={filters.fy} options={values("financial_year")} onChange={(fy) => setFilters((x) => ({ ...x, fy }))} /><Filter label="Governing law" value={filters.law} options={values("governing_act")} onChange={(law) => setFilters((x) => ({ ...x, law }))} /><Filter label="Payment nature" value={filters.nature} options={values("payment_nature")} onChange={(nature) => setFilters((x) => ({ ...x, nature }))} /><Filter label="Deductee type" value={filters.type} options={values("deductee_type")} onChange={(type) => setFilters((x) => ({ ...x, type }))} /><Filter label="Status" value={filters.status} options={values("lifecycle")} onChange={(status) => setFilters((x) => ({ ...x, status }))} /><label className="field"><span>Section / provision</span><input placeholder="Search provision" value={filters.search} onChange={(e) => setFilters((x) => ({ ...x, search: e.target.value }))} /></label></div>
      <div className="table-wrap"><table><thead><tr><th>Payment nature</th><th>Provision & deductee</th><th>Applicability</th><th>Statutory configuration</th><th>Version / status</th><th /></tr></thead><tbody>{rules.map((rule) => <tr key={rule.rule_id}><td><b>{pretty(rule.payment_nature)}</b><br /><span className="muted">{rule.financial_year || "Financial year pending"}</span></td><td>{rule.section_reference || "Provision pending"}<br /><span className="muted">{pretty(rule.deductee_type)}</span></td><td>{pretty(rule.governing_act)}<br /><span className="muted">{rule.effective_from || "—"} to {rule.effective_to || "—"}</span></td><td>{rule.rate ?? "—"}% · {pretty(rule.threshold_type)}<br /><span className="muted">Threshold: {rule.threshold ?? "Not applicable"}</span></td><td><span className={`badge ${rule.active ? "green" : "blue"}`}>{pretty(rule.lifecycle)}</span><br /><span className="muted">{rule.rule_version} · {rule.updated_at?.slice(0, 10) || "—"}</span></td><td><button className="btn secondary small" onClick={() => setSelected(rule)}>View</button></td></tr>)}{!rules.length && <tr><td colSpan={6} className="muted">No rules match these filters.</td></tr>}</tbody></table></div></>}</section>}
    {creating && <RuleWizard draft={draft} step={step} set={set} setStep={setStep} onCancel={() => setCreating(false)} onSave={() => save.mutate()} saving={save.isPending} />}
    {selected && !creating && <RuleDetail rule={selected} onClose={() => setSelected(null)} onVersion={() => version(selected)} onEdit={() => editDraft(selected)} onAction={(kind) => action.mutate({ rule: selected, kind })} />}
  </>;
}

function Filter({ label, value, options, onChange }: { label: string; value: string; options: string[]; onChange: (value: string) => void }) { return <label className="field"><span>{label}</span><select value={value} onChange={(e) => onChange(e.target.value)}><option value="">All</option>{options.map((option) => <option key={option} value={option}>{pretty(option)}</option>)}</select></label>; }
function RuleWizard({ draft, step, set, setStep, onCancel, onSave, saving }: { draft: TdsComplianceRuleDraft; step: number; set: (key: keyof TdsComplianceRuleDraft, value: unknown) => void; setStep: (step: number) => void; onCancel: () => void; onSave: () => void; saving: boolean }) {
  const field = (label: string, key: keyof TdsComplianceRuleDraft, type = "text", placeholder = "") => <label className="field"><span>{label}</span><input type={type} placeholder={placeholder} value={String(draft[key] ?? "")} onChange={(e) => set(key, type === "number" ? Number(e.target.value) : e.target.value)} /></label>;
  return <section className="workspace-section"><div className="section-heading"><div><span className="eyebrow">ADD STATUTORY RULE</span><h2><ClipboardCheck size={16} /> {stepTitles[step]}</h2></div><button className="btn secondary small" onClick={onCancel}><ArrowLeft size={14} /> Back to library</button></div><div className="stepper">{stepTitles.map((title, index) => <span key={title} className={index === step ? "active" : index < step ? "complete" : ""}>{index + 1}. {title}</span>)}</div>
    {step === 0 && <div className="form-grid">{field("Financial Year", "financial_year", "text", "2025-26")}{field("Governing Law", "governing_act", "text", "INCOME_TAX_ACT_1961")}{field("Payment Nature", "payment_nature", "text", "contractor")}{field("Deductee Type", "deductee_type", "text", "INDIVIDUAL_HUF")}{field("Section / Provision", "section_reference")}</div>}
    {step === 1 && <div className="form-grid">{field("Effective From", "effective_from", "date")}{field("Effective To", "effective_to", "date")}{field("Configured PAN treatment rate, if applicable", "no_pan_rate", "text")}<label className="field"><span>Threshold Treatment</span><select value={draft.threshold_type || "NO_THRESHOLD"} onChange={(e) => set("threshold_type", e.target.value)}><option value="NO_THRESHOLD">No threshold</option><option value="PER_TRANSACTION">Per transaction</option><option value="AGGREGATE">Aggregate financial year</option><option value="AGGREGATE_EXCESS">Aggregate excess</option><option value="PER_TRANSACTION_AND_AGGREGATE">Per transaction and aggregate FY</option></select></label></div>}
    {step === 2 && <div className="form-grid">{field("Statutory Rate", "rate")}{field("Threshold Amount", "threshold")}{field("Per-payment threshold", "per_transaction_threshold")}{field("Aggregate FY threshold", "aggregate_financial_year_threshold")}{field("Priority", "priority", "number")}<label className="field"><span>Calculation basis</span><select value={draft.calculation_basis || "full_amount"} onChange={(e) => set("calculation_basis", e.target.value)}><option value="full_amount">Full amount</option><option value="taxable_amount">Taxable amount</option><option value="rule_defined_base">Rule-defined base</option></select></label><label className="field"><span>Rounding policy</span><select value={draft.rounding_method || "HALF_UP"} onChange={(e) => set("rounding_method", e.target.value)}><option value="HALF_UP">Half up</option></select></label></div>}
    {step === 3 && <div className="form-grid">{field("Rule Source", "source")}{field("Source Reference", "source_reference")}{field("Organisation ID", "organization_id")}<label className="field"><span>Rule scope</span><select value={draft.scope} onChange={(e) => set("scope", e.target.value)}><option value="ORGANIZATION">Organisation</option><option value="CLIENT">Client</option><option value="ASSIGNMENT">Assignment</option></select></label>{field("Client ID", "client_id")}{field("Assignment ID", "assignment_id")}</div>}
    {step === 4 && <div className="detail-fields compact"><div className="field"><span>Rule ready for draft submission</span><b>{draft.financial_year || "Financial year pending"} · {draft.payment_nature || "Payment nature pending"} · {draft.section_reference || "Provision pending"}</b></div><div className="field"><span>Statutory configuration</span><b>{draft.rate || "Rate pending"}% · {pretty(draft.threshold_type)} · {draft.threshold || "No threshold amount"}</b></div><div className="field"><span>Source provenance</span><b>{draft.source || "Source pending"} · {draft.source_reference || "Reference pending"}</b></div></div>}
    <div className="button-row"><button className="btn secondary" disabled={step === 0} onClick={() => setStep(step - 1)}>Previous</button>{step < 4 ? <button className="btn primary" onClick={() => setStep(step + 1)}>Continue</button> : <button className="btn primary" disabled={saving} onClick={onSave}>Save Draft</button>}</div></section>;
}
function RuleDetail({ rule, onClose, onVersion, onEdit, onAction }: { rule: TdsComplianceRule; onClose: () => void; onVersion: () => void; onEdit: () => void; onAction: (kind: "submit" | "approve" | "activate" | "deactivate") => void }) { const history = useQuery({ queryKey: ["rule-history", rule.rule_id], queryFn: () => api.tdsComplianceRuleHistory(rule.rule_id) }); const audit = useQuery({ queryKey: ["rule-audit", rule.rule_id], queryFn: () => api.tdsComplianceRuleAudit(rule.rule_id) }); return <section className="workspace-section"><div className="section-heading"><div><span className="eyebrow">RULE DETAIL</span><h2>{rule.section_reference || rule.rule_id}</h2></div><button className="btn secondary small" onClick={onClose}>Close</button></div><div className="detail-fields compact"><Detail label="Rule identity" value={`${rule.rule_id} · ${rule.rule_version}`} /><Detail label="Applicability" value={`${rule.financial_year || "—"} · ${pretty(rule.payment_nature)} · ${pretty(rule.deductee_type)}`} /><Detail label="Effective period" value={`${rule.effective_from || "—"} to ${rule.effective_to || "—"}`} /><Detail label="Calculation parameters" value={`${rule.rate ?? "—"}% · ${pretty(rule.threshold_type)} · ${rule.threshold ?? "No threshold amount"}`} /><Detail label="Legal / source reference" value={`${rule.source || "—"} · ${rule.source_reference || "—"}`} /><Detail label="Governance" value={`${pretty(rule.lifecycle)} · Updated ${rule.updated_at?.slice(0, 10) || "—"}`} /></div><div className="button-row">{rule.lifecycle === "ACTIVE" && <button className="btn primary" onClick={onVersion}>Create Version</button>}{rule.lifecycle === "DRAFT" && <button className="btn secondary" onClick={onEdit}>Edit Draft</button>}{rule.lifecycle === "DRAFT" && <button className="btn primary" onClick={() => onAction("submit")}>Submit for Approval</button>}{rule.lifecycle === "PENDING_APPROVAL" && <button className="btn primary" onClick={() => onAction("approve")}>Approve</button>}{rule.lifecycle === "APPROVED" && <button className="btn primary" onClick={() => onAction("activate")}>Activate</button>}{["APPROVED", "ACTIVE"].includes(rule.lifecycle) && <button className="btn secondary" onClick={() => onAction("deactivate")}>Deactivate</button>}</div><div className="detail-fields compact"><Detail label="Version history" value={history.data?.map((item: any) => item.action).join(" · ") || "No history recorded"} /><Detail label="Audit trail" value={audit.data?.map((item: any) => `${item.action} — ${item.timestamp?.slice(0, 10)}`).join(" · ") || "No audit events recorded"} /></div></section>; }
function Detail({ label, value }: { label: string; value: string }) { return <div className="field"><span>{label}</span><b>{value}</b></div>; }
