import { useEffect, useState } from "react";
import { useMutation, useQuery, useQueryClient } from "@tanstack/react-query";
import { ArrowRight, ClipboardList, FileCheck2, LockKeyhole, ShieldAlert, ShieldCheck } from "lucide-react";
import { useNavigate } from "react-router-dom";
import { ErrorNotice, InfoNotice, PageHeader } from "../components/common";
import { api, getErrorMessage } from "../services/api";
import type { TdsComplianceAssignment, TdsComplianceWorkspace } from "../types";

const humanize = (value?: string | null) => value ? value.replaceAll("_", " ").replace(/\b\w/g, letter => letter.toUpperCase()) : "Not available";
const displayCount = (value: number | null | undefined) => value == null ? "Not available" : String(value);
const stageTone = (status: string) => status === "COMPLETED" ? "green" : status === "BLOCKED" ? "red" : status === "IN_PROGRESS" ? "amber" : "slate";

function Metric({ label, value, detail }: { label: string; value: number | null | undefined; detail: string }) {
  return <article className="tds-workspace-metric"><span>{label}</span><strong>{displayCount(value)}</strong><small>{detail}</small></article>;
}

function WorkspaceBody({ workspace, onLock }: { workspace: TdsComplianceWorkspace; onLock: () => void }) {
  const navigate = useNavigate();
  const { assignment, overview, stages, sources, exceptions } = workspace;
  return <>
    <div className="context-strip tds-context-strip"><div><span>ASSESSEE / COMPANY</span><b>{assignment.assessee_legal_name}</b></div><div><span>PAN</span><b>{assignment.assessee_pan || "Not provided"}</b></div><div><span>TAN</span><b>{assignment.tan || "Not provided"}</b></div><div><span>FINANCIAL YEAR / QUARTER</span><b>{assignment.financial_year}{assignment.quarter ? ` · ${assignment.quarter}` : " · All quarters"}</b></div><div><span>WORKFLOW STAGE</span><b>{humanize(overview.workflow_stage)}</b></div><div><span>LOCK STATE</span><b>{humanize(overview.lock_status)}</b></div></div>
    <section className="tds-workspace-summary"><div className="tds-summary-heading"><div><span className="eyebrow">CURRENT COMPLIANCE POSITION</span><h2>{overview.overall_review_state === "LOCKED" ? "Assignment is locked" : overview.exceptions ? "Review items need attention" : "Compliance review is in progress"}</h2><p>Stage: {humanize(overview.workflow_stage)} · Last updated: {overview.last_updated ? new Date(overview.last_updated).toLocaleString() : "Not recorded"}</p></div><span className={`badge ${overview.lock_status === "LOCKED" ? "slate" : overview.exceptions ? "amber" : "blue"}`}>{humanize(overview.overall_review_state)}</span></div><div className="tds-metrics-grid"><Metric label="Ledger transactions" value={overview.transactions_uploaded} detail="Current committed ledger version" /><Metric label="Classified" value={overview.transactions_classified} detail="Payment-nature decisions available" /><Metric label="Calculated" value={overview.transactions_calculated} detail="Persisted calculation-result rows" /><Metric label="Exceptions" value={overview.exceptions} detail="Controlled review items" /><Metric label="Deposit issues" value={overview.deposit_issues} detail="Latest deposit-compliance run" /><Metric label="Interest issues" value={overview.interest_issues} detail="Latest interest-compliance run" /></div><div className="tds-workspace-actions"><button className="primary-button" onClick={() => navigate("/tds-compliance/assignments")}>Open assignment workflow <ArrowRight size={15} /></button><button className="secondary-button" onClick={() => navigate("/tds-compliance/calculator")}>Open TDS calculator</button><button className="secondary-button" onClick={() => navigate("/tds-compliance/deposit")}>Review deposit evidence</button>{assignment.status !== "LOCKED" && <button className="secondary-button danger" onClick={onLock}><LockKeyhole size={14} /> Lock assignment</button>}</div></section>
    <div className="tds-overview-grid"><section className="workspace-section"><div className="section-heading"><div><span className="eyebrow">COMPLIANCE JOURNEY</span><h2>Workflow progress</h2><p className="muted">Each stage is derived from persisted TDS Compliance records.</p></div><ClipboardList size={20} /></div><ol className="tds-stage-list">{stages.map((stage, index) => <li key={stage.key}><span className={`tds-stage-number ${stageTone(stage.status)}`}>{index + 1}</span><div><b>{stage.label}</b><small>{stage.detail}</small></div><span className={`badge ${stageTone(stage.status)}`}>{humanize(stage.status)}</span></li>)}</ol></section><section className="workspace-section"><div className="section-heading"><div><span className="eyebrow">REQUIRED DATA</span><h2>Source readiness</h2><p className="muted">Only committed source versions are treated as available evidence.</p></div><FileCheck2 size={20} /></div><div className="tds-source-list">{sources.map(source => <article key={source.key}><div><b>{source.label}</b><small>{source.detail || "No source record available"}</small></div><div className="tds-source-status"><span className={`badge ${source.committed ? "green" : "slate"}`}>{source.committed ? "Committed" : "Not provided"}</span><small>{source.committed ? `v${source.version} · ${displayCount(source.row_count)} rows` : "Upload and commit required"}{source.validation_issues != null ? ` · ${source.validation_issues} validation issues` : ""}</small></div></article>)}</div></section></div>
    <section className="workspace-section"><div className="section-heading"><div><span className="eyebrow">EXCEPTION SUMMARY</span><h2>Items that need CA attention</h2><p className="muted">Counts are drawn from the latest persisted workflow records; unavailable downstream workflows are explicit.</p></div><ShieldAlert size={20} /></div><div className="tds-exception-grid">{Object.entries(exceptions).map(([key, value]) => <article key={key}><span>{humanize(key)}</span><b>{displayCount(value)}</b><small>{value == null ? "Workflow not implemented or no persisted source" : value ? "Open the assignment workflow to review records" : "No issue in the latest available run"}</small></article>)}</div><InfoNotice tone="info">Government reconciliation and return evidence have no persisted TDS Compliance workflow yet. They remain not started; no counts have been invented.</InfoNotice></section>
  </>;
}

export default function TdsComplianceOverviewPage() {
  const queryClient = useQueryClient(); const assignments = useQuery({ queryKey: ["tds-compliance-assignments"], queryFn: api.tdsComplianceAssignments }); const [assignmentId, setAssignmentId] = useState("");
  const workspace = useQuery({ queryKey: ["tds-compliance-workspace", assignmentId], queryFn: () => api.tdsComplianceWorkspace(assignmentId), enabled: Boolean(assignmentId) });
  useEffect(() => { if (!assignmentId && assignments.data?.length) setAssignmentId(assignments.data[0].assignment_id); }, [assignmentId, assignments.data]);
  const lock = useMutation({ mutationFn: () => api.lockTdsComplianceAssignment(assignmentId), onSuccess: () => { void queryClient.invalidateQueries({ queryKey: ["tds-compliance-assignments"] }); void queryClient.invalidateQueries({ queryKey: ["tds-compliance-workspace", assignmentId] }); } });
  return <><PageHeader eyebrow="TDS COMPLIANCE" title="Compliance workspace" subtitle="Review the selected deductor assignment, evidence readiness, calculation progress, and controlled review items." />{assignments.isError && <ErrorNotice message={getErrorMessage(assignments.error, "TDS Compliance assignments could not be loaded.")} onRetry={() => assignments.refetch()} />}{!assignments.isLoading && !assignments.data?.length && <section className="workspace-section empty-state"><ShieldCheck size={30} /><h3>No TDS Compliance assignments yet</h3><p>Create a controlled draft assignment before uploading a payment ledger or running TDS compliance work.</p></section>}{!!assignments.data?.length && <section className="workspace-section tds-assignment-selector"><label><span className="eyebrow">ACTIVE ASSIGNMENT</span><select value={assignmentId} onChange={event => setAssignmentId(event.target.value)}>{assignments.data.map((item: TdsComplianceAssignment) => <option key={item.assignment_id} value={item.assignment_id}>{item.assessee_legal_name} · FY {item.financial_year} · {item.tan || "TAN pending"}</option>)}</select></label></section>}{workspace.isLoading && <section className="workspace-section"><p className="muted">Loading the persisted compliance workspace…</p></section>}{workspace.isError && <ErrorNotice message={getErrorMessage(workspace.error, "The selected assignment workspace could not be loaded.")} onRetry={() => workspace.refetch()} />}{workspace.data && <WorkspaceBody workspace={workspace.data} onLock={() => lock.mutate()} />}{lock.isError && <ErrorNotice message={getErrorMessage(lock.error, "The assignment could not be locked.")} />}</>;
}
