import { useEffect, useState } from "react";
import { Calculator, History, Save } from "lucide-react";
import { ErrorNotice, InfoNotice, StatCard } from "../components/common";
import { api, getErrorMessage } from "../services/api";
import type { TdsCalculatorInput, TdsCalculatorRecord, TdsCalculatorResult, TdsComplianceAssignment } from "../types";
import "./tds-calculator.css";

const blank = (financial_year: string): TdsCalculatorInput => ({ financial_year, payment_nature: "", amount: "", payment_mode: "GROSS", credit_date: "", payment_date: "", deductee_type: "", deductee_pan: "" });
const money = (value?: number | null) => value == null ? "â€”" : `â‚¹${value.toLocaleString("en-IN", { maximumFractionDigits: 2 })}`;
const label = (value?: string | null) => value ? value.replaceAll("_", " ").replace(/\b\w/g, char => char.toUpperCase()) : "â€”";
type PaymentOption = { payment_nature: string; provision?: string | null; governing_act?: string | null };

export default function TdsCalculatorWorkspace({ assignment, presentationMode = false }: { assignment: TdsComplianceAssignment; presentationMode?: boolean }) {
  const [mode, setMode] = useState<"QUICK" | "DETAILED">("QUICK"); const [form, setForm] = useState<TdsCalculatorInput>(() => blank(assignment.financial_year)); const [result, setResult] = useState<TdsCalculatorResult | null>(null); const [history, setHistory] = useState<TdsCalculatorRecord[]>([]); const [options, setOptions] = useState<PaymentOption[]>([]); const [catalogError, setCatalogError] = useState(""); const [busy, setBusy] = useState(false); const [error, setError] = useState(""); const [message, setMessage] = useState("");
  const update = (key: keyof TdsCalculatorInput, value: string) => { setForm(current => ({ ...current, [key]: value })); setResult(null); setMessage(""); };
  useEffect(() => { setForm(blank(assignment.financial_year)); setResult(null); if (!presentationMode) void api.tdsCalculatorHistory(assignment.assignment_id).then(setHistory).catch(() => setHistory([])); }, [assignment.assignment_id, assignment.financial_year, presentationMode]);
  useEffect(() => { const load = api.tdsCalculatorOptions; if (!load) return; setCatalogError(""); void load(assignment.financial_year).then(items => { setOptions(items); if (!items.length) setCatalogError("No verified statutory payment natures are available for this financial year."); }).catch(() => { setOptions([]); setCatalogError("The verified statutory catalog could not be loaded. Try again after the service is available."); }); }, [assignment.financial_year]);
  const submit = async (save: boolean) => { setBusy(true); setError(""); setMessage(""); try { let next: TdsCalculatorResult; if (presentationMode) next = await api.previewStandaloneTdsCalculator(form); else if (save) { const record = await api.saveTdsCalculator(assignment.assignment_id, form); next = record.result; setHistory(current => [record, ...current]); } else next = await api.previewTdsCalculator(assignment.assignment_id, form); setResult(next); setMessage(next.status === "CALCULATED" ? (save ? "Calculation saved." : "Calculation determined from the active statutory rule.") : "Calculation requires statutory rule configuration."); } catch (reason) { setError(getErrorMessage(reason, "Complete the payment details and check the statutory rule configuration.")); } finally { setBusy(false); } };
  const field = (name: keyof TdsCalculatorInput, title: string, type = "text", required = false) => <label>{title}<input type={type} required={required} value={String(form[name] || "")} onChange={event => update(name, event.target.value)} /></label>;
  const calculated = result?.status === "CALCULATED";
  return <section className="workspace-section tds-calculator-tool" id="tds-calculator"><div className="section-heading"><div><span className="eyebrow">TDS CALCULATOR</span><h2>Calculate TDS for a payment</h2><p className="muted">Enter transaction details. The system selects the rate and threshold from active approved statutory rules.</p></div><Calculator size={21} /></div>
    <div className="calculator-mode" role="tablist"><button className={mode === "QUICK" ? "primary-button" : "secondary-button"} onClick={() => setMode("QUICK")}>Quick calculation</button><button className={mode === "DETAILED" ? "primary-button" : "secondary-button"} onClick={() => setMode("DETAILED")}>Advanced details</button></div>
    <form className="form-grid tds-calculator-form" onSubmit={event => { event.preventDefault(); void submit(false); }}><label>Payment nature<select required value={form.payment_nature} onChange={event => update("payment_nature", event.target.value)}><option value="">Choose payment nature</option>{options.map(option => <option key={option.payment_nature} value={option.payment_nature}>{label(option.payment_nature)}{option.provision ? ` â€” ${option.provision}` : ""}</option>)}</select></label>{field("amount", form.payment_mode === "GROSS" ? "Payment amount" : "Net payment amount", "number", true)}<label>Payment mode<select value={form.payment_mode} onChange={event => update("payment_mode", event.target.value)}><option value="GROSS">Gross payment</option><option value="NET_OF_TDS">Net of TDS</option></select></label>{field("credit_date", "Credit date", "date", true)}{field("payment_date", "Payment date", "date", true)}<label>Recipient residency<select value={form.recipient_residency || ""} onChange={event => update("recipient_residency", event.target.value)}><option value="">Unknown / requires review</option><option value="RESIDENT">Resident in India</option><option value="NON_RESIDENT">Non-resident</option><option value="FOREIGN_COMPANY">Foreign company</option></select></label><label>Deductee type<select value={form.deductee_type || ""} onChange={event => update("deductee_type", event.target.value)}><option value="">Select deductee type</option><option value="INDIVIDUAL_HUF">Individual / HUF</option><option value="COMPANY">Company / other person</option><option value="INDIVIDUAL">Individual</option><option value="HUF">HUF</option></select></label>{field("deductee_pan", "Deductee PAN")}
      {mode === "DETAILED" && <><label>Recipient category<select value={form.recipient_category || ""} onChange={event => update("recipient_category", event.target.value)}><option value="">Not yet classified</option><option value="PERSON">Person</option><option value="INDIVIDUAL_HUF">Individual / HUF</option><option value="DOMESTIC_COMPANY">Domestic company</option><option value="FOREIGN_COMPANY">Foreign company</option><option value="SENIOR_CITIZEN">Senior citizen</option><option value="COOPERATIVE_SOCIETY">Co-operative society</option><option value="PARTNER">Partner</option><option value="UNITHOLDER">Unitholder</option></select></label><label>Payer category<select value={form.payer_category || ""} onChange={event => update("payer_category", event.target.value)}><option value="">Not yet classified</option><option value="ANY_PAYER">Any payer</option><option value="DESIGNATED_PERSON">Designated person</option><option value="QUALIFYING_INDIVIDUAL_HUF">Qualifying individual / HUF</option><option value="BANK_COOPERATIVE_BANK_POST_OFFICE">Bank / co-op bank / post office</option><option value="COMPANY">Company</option><option value="FIRM">Firm</option><option value="ECOMMERCE_OPERATOR">E-commerce operator</option></select></label>{field("previous_aggregate_amount", "Previous aggregate amount", "number")}{field("taxable_amount", "Taxable base", "number")}{field("actual_tds_deducted", "Actual TDS deducted", "number")}{field("deduction_date", "Actual deduction date", "date")}{field("actual_deposit_date", "Actual deposit date", "date")}{field("certificate_number", "Lower/nil certificate number")}{field("certificate_rate", "Certificate rate", "number")}{field("certificate_valid_from", "Certificate valid from", "date")}{field("certificate_valid_to", "Certificate valid to", "date")}</>}
      <div className="wizard-actions calculator-actions"><button className="primary-button" type="submit" disabled={busy}>{busy ? "Calculatingâ€¦" : "Calculate TDS"}</button>{!presentationMode && <button className="secondary-button" type="button" disabled={busy || assignment.status === "LOCKED"} onClick={() => void submit(true)}><Save size={14} /> Save calculation</button>}</div></form>
    {catalogError && <InfoNotice tone="warning">{catalogError}</InfoNotice>}{error && <ErrorNotice message={error} />}{message && <InfoNotice tone={calculated ? "info" : "warning"}>{message}</InfoNotice>}
    {result && !calculated && <section className="calculator-not-determinable"><span className="eyebrow">CALCULATION CANNOT BE DETERMINED</span><h3>No active approved TDS rule is configured for this transaction.</h3><div className="detail-grid"><dt>Financial year</dt><dd>{form.financial_year}</dd><dt>Payment nature</dt><dd>{label(form.payment_nature)}</dd><dt>Deductee type</dt><dd>{label(form.deductee_type)}</dd><dt>Effective date</dt><dd>{form.credit_date || form.payment_date || "Not provided"}</dd><dt>Rule matching status</dt><dd>{label(result.reason_code || result.status)}</dd></div><a className="primary-button" href="/tds-compliance/settings">View TDS Rule Configuration</a></section>}
    {calculated && result && <><div className="stat-grid tds-calculator-results"><StatCard label="Applicable provision" value={result.provision || "â€”"} icon={Calculator} /><StatCard label="Applicable rate" value={result.tds_rate == null ? "â€”" : `${result.tds_rate}%`} icon={Calculator} /><StatCard label="Calculated TDS" value={money(result.tds_amount)} icon={Calculator} /><StatCard label="Net payment" value={money(result.net_payment)} icon={Calculator} /><StatCard label="Deposit due date" value={result.deposit_due_date || "â€”"} icon={Calculator} /><StatCard label="Interest" value={money(result.interest?.total_interest)} icon={Calculator} /></div><div className="detail-grid"><dt>Threshold assessment</dt><dd>{label(result.threshold_status)}</dd><dt>Governing law</dt><dd>{label(result.governing_act)}</dd><dt>Actual TDS deducted</dt><dd>{money(result.actual_tds_deducted)}</dd><dt>Rule version</dt><dd>{result.rule_version || "â€”"}</dd></div><details className="calculator-explanation"><summary>Why was this rule applied?</summary><p>Financial year, governing law, payment nature, deductee type, effective date, scope, and active approval status matched the controlled statutory rule.</p><p>Threshold assessment: {label(result.threshold_status)}. Rule source: {String(result.rule_snapshot?.source || "Not recorded")} Â· {String(result.rule_snapshot?.source_reference || "Not recorded")}.</p></details>{result.warnings.map((warning, index) => <InfoNotice key={index} tone="warning">{warning}</InfoNotice>)}</>}
    {!presentationMode && <section className="workspace-section calculator-history"><div className="section-heading"><div><span className="eyebrow">SAVED CALCULATIONS</span><h3>Calculation history</h3></div><History size={18} /></div>{history.length ? <div className="table-scroll"><table className="data-table"><thead><tr><th>Calculation ID</th><th>Created</th><th>Nature</th><th>TDS</th><th>Provision</th><th>Status</th></tr></thead><tbody>{history.map(item => <tr key={item.calculator_run_id} onClick={() => setResult(item.result)}><td>{item.calculator_run_id}</td><td>{item.created_at}</td><td>{label(item.input.payment_nature)}</td><td>{money(item.result.tds_amount)}</td><td>{item.result.provision || "â€”"}</td><td>{label(item.result.status)}</td></tr>)}</tbody></table></div> : <p className="muted">Saved calculations will appear here.</p>}</section>}
  </section>;
}
