import { act } from "react";
import { createRoot, type Root } from "react-dom/client";
import TdsCalculatorWorkspace from "./TdsCalculatorWorkspace";

Object.assign(globalThis, { IS_REACT_ACT_ENVIRONMENT: true });
const mockPreview = jest.fn(); const mockSave = jest.fn(); const mockHistory = jest.fn(); const mockOptions = jest.fn();
jest.mock("../services/api", () => ({ api: { previewTdsCalculator: (...args: unknown[]) => mockPreview(...args), saveTdsCalculator: (...args: unknown[]) => mockSave(...args), tdsCalculatorHistory: (...args: unknown[]) => mockHistory(...args), tdsCalculatorOptions: (...args: unknown[]) => mockOptions(...args) }, getErrorMessage: () => "Controlled API error" }));
const assignment = { assignment_id: "A", client_id: "C", organization_id: "O", assessee_legal_name: "Acme", financial_year: "2026-27", workflow: "TDS_COMPLIANCE", status: "DRAFT", created_at: "", updated_at: "", version: 1 } as const;
const result = { status: "CALCULATED", warnings: ["Actual deposit date not provided; interest cannot be determined."], governing_act: "INCOME_TAX_ACT_2025", provision: "393(1), Table 1", tds_rate: 10, tds_amount: 10000, gross_amount: 100000, net_payment: 90000, taxable_tds_base: 100000, threshold_amount: null, threshold_consumed: null, threshold_excess: 100000, deduction_date: "2026-04-15", deposit_due_date: "2026-05-07", interest_status: "DEPOSIT_DATE_NOT_PROVIDED", interest: { total_interest: null }, rule_id: "R1", rule_version: "2026.1" };
const setInput = (input: HTMLInputElement | HTMLSelectElement, value: string) => { Object.getOwnPropertyDescriptor(Object.getPrototypeOf(input), "value")?.set?.call(input, value); input.dispatchEvent(new Event("change", { bubbles: true })); };
describe("TDS calculator workspace", () => {
  let host: HTMLDivElement; let root: Root;
  beforeEach(() => { host = document.createElement("div"); document.body.appendChild(host); root = createRoot(host); mockPreview.mockReset(); mockSave.mockReset(); mockHistory.mockResolvedValue([]); mockOptions.mockResolvedValue([{ payment_nature: "professional_fee", provision: "393(1), Table 1" }]); mockPreview.mockResolvedValue(result); });
  afterEach(() => { act(() => root.unmount()); host.remove(); });
  test("renders the compact calculator and opens advanced details on demand", async () => { await act(async () => { root.render(<TdsCalculatorWorkspace assignment={assignment} />); }); expect(host.textContent).toContain("Calculate TDS for a payment"); expect(host.textContent).toContain("Quick calculation"); expect(host.textContent).toContain("Advanced details"); expect(host.textContent).not.toContain("Phase 3 selects"); await act(async () => { Array.from(host.querySelectorAll("button")).find(b => b.textContent === "Advanced details")?.click(); }); expect(host.textContent).toContain("Previous aggregate amount"); expect(host.textContent).toContain("Lower/nil certificate number"); });
  test("posts preview and presents configured result cards and warning", async () => { await act(async () => { root.render(<TdsCalculatorWorkspace assignment={assignment} />); }); const nature = host.querySelector<HTMLSelectElement>("select")!; await act(async () => { setInput(nature, "professional_fee"); }); const inputs = host.querySelectorAll<HTMLInputElement>("input"); await act(async () => { setInput(inputs[0], "100000"); setInput(inputs[1], "2026-04-15"); setInput(inputs[2], "2026-04-20"); }); await act(async () => { host.querySelector<HTMLFormElement>("form")!.dispatchEvent(new Event("submit", { bubbles: true, cancelable: true })); }); expect(mockPreview.mock.calls[0][0]).toBe("A"); expect(mockPreview.mock.calls[0][1].payment_nature).toBe("professional_fee"); expect(mockPreview.mock.calls[0][1].amount).toBe("100000"); expect(host.textContent).toContain("â‚¹10,000"); expect(host.textContent).toContain("393(1), Table 1"); expect(host.textContent).toContain("Actual deposit date not provided"); });
  test("API failures are controlled", async () => { mockPreview.mockRejectedValue(new Error("secret stack")); await act(async () => { root.render(<TdsCalculatorWorkspace assignment={assignment} />); }); await act(async () => { host.querySelector<HTMLFormElement>("form")!.dispatchEvent(new Event("submit", { bubbles: true, cancelable: true })); }); expect(host.textContent).toContain("Controlled API error"); expect(host.textContent).not.toContain("secret stack"); });
});
