import { useState } from 'react';
import { ClipboardCheck } from 'lucide-react';
import { Amount, EmptyState, InfoNotice, Pagination, StatCard, Field } from '../../components/common';
import * as Dialog from '@radix-ui/react-dialog';
import type { Context, DepositResult, DepositRun, Evidence, EvidenceVersion, Summary } from './types';
import { label, money, provided } from './format';

export function Badge({ value }: { value?: string | null }) {
  const tone = value && /COMPLIANT|ON_TIME|MATCHED|ESTABLISHED|VALID|APPROVED/.test(value) && !/INVALID|UNMATCHED/.test(value) ? 'green' : value && /EXCEPTION|SHORT|EXCESS|INVALID|AMBIGUOUS|REVIEW|MISSING/.test(value) ? 'amber' : 'slate';
  return <span className={`badge ${tone}`}>{label(value)}</span>;
}
export function SummaryCards({ summary }: { summary?: Summary | null }) {
  const counts: [string, number | undefined][] = [['Total Liabilities', summary?.liability_count], ['Deposit Evidence Rows', summary?.evidence_count], ['Reconciled', summary?.reconciled_count], ['Compliant', summary?.compliant_count], ['Review Required', summary?.review_required_count], ['Exceptions', summary?.exception_count], ['Not Determinable', summary?.not_determinable_count]];
  const difference = summary?.deposited_tds_total != null && summary.expected_tds_total != null ? summary.deposited_tds_total - summary.expected_tds_total : null;
  return <div className="phase5-summary" data-testid="phase5-summary">{counts.map(([name, value]) => <StatCard key={name} label={name} value={value == null ? 'Not Determinable' : String(value)} icon={ClipboardCheck} />)}
    {[['Expected TDS', summary?.expected_tds_total], ['Matched Deposit Amount', summary?.deposited_tds_total], ['Difference (deposit − expected)', difference]].map(([name, value]) => <StatCard key={String(name)} label={String(name)} value={money(value as number | null | undefined)} icon={ClipboardCheck} detail={name === 'Matched Deposit Amount' ? 'Source evidence; not government verification' : undefined} />)}
  </div>;
}
function SourceAmount({ value }: { value?: number | null }) { return value == null ? <>Not Provided</> : <Amount value={value} />; }
export function EvidenceTable({ rows, version }: { rows: Evidence[]; version?: EvidenceVersion | null }) {
  const [search, setSearch] = useState(''), [status, setStatus] = useState(''), [page, setPage] = useState(1);
  const filtered = rows.filter(r => (!status || r.validation_status === status) && [r.evidence_id, r.tan, r.challan_number, r.cin, r.bsr_code, r.source_reference, r.financial_year].some(v => (v || '').toLowerCase().includes(search.toLowerCase())));
  const current = Math.min(page, Math.max(1, Math.ceil(filtered.length / 25)));
  return <><div className="filter-bar"><label>Search evidence<input aria-label="Search evidence" value={search} onChange={e => { setSearch(e.target.value); setPage(1); }} placeholder="Evidence, TAN, challan or source" /></label><label>Validation status<select value={status} onChange={e => { setStatus(e.target.value); setPage(1); }}><option value="">All statuses</option>{Array.from(new Set(rows.map(r => r.validation_status))).map(s => <option key={s} value={s}>{label(s)}</option>)}</select></label></div>
    {!rows.length ? <EmptyState title="No evidence rows" text="No deposit evidence has been committed for this assignment." /> : <><div className="table-scroll"><table className="data-table"><caption className="sr-only">Deposit evidence</caption><thead><tr>{['Evidence ID', 'TAN', 'Challan Number', 'CIN', 'BSR', 'Deposit Date', 'TDS Deposit Amount', 'FY', 'Source Reference', 'Version', 'Validation Status'].map(h => <th key={h}>{h}</th>)}</tr></thead><tbody>{filtered.slice((current - 1) * 25, current * 25).map((r, i) => <tr key={`${r.evidence_id}-${r.source_row_number}-${i}`}><td>{provided(r.evidence_id)}</td><td>{provided(r.tan)}</td><td>{provided(r.challan_number)}</td><td>{provided(r.cin)}</td><td>{provided(r.bsr_code)}</td><td>{provided(r.deposit_date)}</td><td><SourceAmount value={r.tds_amount} /></td><td>{provided(r.financial_year)}</td><td>{provided(r.source_reference)}<small className="phase5-block">{provided(r.source_file_name)} · Row {provided(r.source_row_number)}</small></td><td>{version ? `V${version.version}` : provided(r.evidence_version_id)}</td><td><Badge value={r.validation_status} />{r.validation_issues?.map((issue, n) => <small className="phase5-block" key={n}>{issue}</small>)}</td></tr>)}</tbody></table></div>{!filtered.length && <p>No evidence matches these filters.</p>}<Pagination page={current} pageSize={25} total={filtered.length} onPage={setPage} /></>}
  </>;
}
export function DetailDrawer({ row, context, run, version, onClose }: { row: DepositResult | null; context: Context; run?: DepositRun | null; version?: EvidenceVersion | null; onClose: () => void }) {
  const liability = context.liabilities.find(l => l.transaction_id === row?.transaction_id);
  const timing = context.timing.find(t => t.transaction_id === row?.transaction_id);
  return <Dialog.Root open={!!row} onOpenChange={open => !open && onClose()}><Dialog.Portal><Dialog.Overlay className="phase5-overlay" /><Dialog.Content className="phase5-detail"><header className="drawer-head"><div><Dialog.Title>Deposit compliance detail · {row?.transaction_id}</Dialog.Title><Dialog.Description>{run ? 'Historical snapshot · Read-only' : 'Preview · Not a committed run'}</Dialog.Description></div><Dialog.Close className="icon-button" aria-label="Close deposit detail">×</Dialog.Close></header>{row && <div className="drawer-body">
    <section><h3>Liability</h3><div className="phase5-fields"><Field label="Liability ID">{row.transaction_id}</Field><Field label="Deductee">{provided(liability?.deductee_name)}</Field><Field label="PAN">{provided(liability?.deductee_pan)}</Field><Field label="TAN">{provided(liability?.tan)}</Field><Field label="Expected TDS">{money(row.expected_tds)}</Field><Field label="Financial Year">{provided(liability?.financial_year)}</Field><Field label="Payment nature">{provided(liability?.payment_nature)}</Field><Field label="Event date">{provided(liability?.effective_event_date)}</Field><Field label="Source reference">{provided(liability?.source_reference)}</Field></div></section>
    <section><h3>Deposit Evidence</h3>{!row.evidence_entries.length && <InfoNotice tone="warning">Deposit evidence not provided or not uniquely mapped.</InfoNotice>}{row.evidence_entries.map((e, i) => <article className="phase5-evidence-card" key={`${e.evidence_id}-${i}`}><h4>Evidence {provided(e.evidence_id)}</h4><div className="phase5-fields"><Field label="Challan">{provided(e.challan_number)}</Field><Field label="CIN">{provided(e.cin)}</Field><Field label="BSR">{provided(e.bsr_code)}</Field><Field label="Deposit date">{provided(e.deposit_date)}</Field><Field label="TDS amount"><SourceAmount value={e.tds_amount} /></Field><Field label="Source reference">{provided(e.source_reference)}</Field><Field label="Source file / row">{provided(e.source_file_name)} / {provided(e.source_row_number)}</Field><Field label="Evidence version">{provided(row.evidence_version_id)}</Field></div></article>)}</section>
    <section><h3>Relationship</h3><Badge value={row.relationship_status} /><div className="phase5-fields"><Field label="Mapping method">{label(row.match_method)}</Field><Field label="Relationship ID">{provided(row.relationship_id)}</Field><Field label="Linked liabilities">{row.liability_ids?.join(', ') || row.transaction_id}</Field><Field label="Allocation">{row.allocation == null ? 'Not Provided' : money(row.allocation)}</Field><Field label="Liability amount">{money(row.expected_tds)}</Field><Field label="Evidence amount">{money(row.deposited_tds)}</Field></div>{(row.liability_ids?.length || 0) > 1 && <InfoNotice>Shared evidence across liabilities: {row.liability_ids?.join(', ')}. Allocation is shown only when supplied.</InfoNotice>}{row.candidate_evidence_ids?.length ? <InfoNotice tone="warning">Manual Review Required. Candidate evidence: {row.candidate_evidence_ids.join(', ')}. A controlled review action is not available in this workspace.</InfoNotice> : null}</section>
    <section><h3>Timeliness</h3><div className="phase5-fields"><Field label="Deduction date">{provided(timing?.actual_deduction_date)}</Field><Field label="Deposit dates">{row.evidence_entries.map(e => provided(e.deposit_date)).join(', ') || 'Not Provided'}</Field><Field label="Due date">{provided(timing?.deposit_due_date)}</Field><Field label="Timeliness"><Badge value={row.timeliness_status} /></Field><Field label="Interest status">{label(row.interest_status)}</Field><Field label="Interest run">{provided(run?.interest_run_id)}</Field></div>{row.timeliness_status === 'INVALID_DATE_SEQUENCE' && <InfoNotice tone="warning">Deposit date precedes deduction date — Manual Review Required.</InfoNotice>}</section>
    <section><h3>Compliance</h3><Badge value={row.overall_status} /><p>{row.reason || 'Reason not provided'}</p><Field label="Reason code">{provided(row.reason_code)}</Field>{row.recommended_action && <Field label="Recommended action">{row.recommended_action}</Field>}</section>
    <section><h3>Provenance &amp; Versions</h3><div className="phase5-fields"><Field label="Evidence version">{version ? `V${version.version} · ${version.evidence_version_id}` : provided(row.evidence_version_id)}</Field><Field label="Compliance run">{run?.deposit_run_id || 'Preview — not committed'}</Field><Field label="Policy version">{row.phase5_rule_snapshot ? `${row.phase5_rule_snapshot.policy_id} · V${row.phase5_rule_snapshot.policy_version}` : 'Not Determinable'}</Field><Field label="Calculation">{provided(row.calculation_id || run?.calculation_id)}</Field><Field label="Created">{provided(run?.created_at)}</Field><Field label="Actor">{provided(run?.created_by)}</Field></div>{row.phase5_rule_snapshot && <p>Frozen policy: {label(row.phase5_rule_snapshot.allocation_policy)} · {label(row.phase5_rule_snapshot.ambiguity_policy)} · Effective {row.phase5_rule_snapshot.effective_from} to {row.phase5_rule_snapshot.effective_to}</p>}</section>
  </div>}</Dialog.Content></Dialog.Portal></Dialog.Root>;
}
export function ResultsTable({ rows, context, onDetail }: { rows: DepositResult[]; context: Context; onDetail: (r: DepositResult) => void }) {
  const [search, setSearch] = useState(''), [filters, setFilters] = useState<Record<string, string>>({}), [page, setPage] = useState(1);
  const data = rows.map(r => { const l = context.liabilities.find(l => l.transaction_id === r.transaction_id); return { row: r, overall: r.overall_status, timeliness: r.timeliness_status, relationship: r.relationship_status || 'NOT_PROVIDED', fy: l?.financial_year || '', pan: l?.deductee_pan || '', deductee: l?.deductee_name || '', tan: Array.from(new Set(r.evidence_entries.map(e => e.tan).filter(Boolean))).join(', '), challan: r.evidence_entries.map(e => e.challan_number).filter(Boolean).join(', '), evidence: r.evidence_entries.map(e => e.evidence_id).join(', ') }; });
  const keys = ['overall', 'timeliness', 'relationship', 'fy', 'pan', 'tan', 'deductee', 'challan'] as const;
  const filtered = data.filter(d => keys.every(k => !filters[k] || d[k] === filters[k]) && (!filters.attention || (filters.attention === 'review' ? d.overall === 'REVIEW_REQUIRED' : d.overall.includes('EXCEPTION'))) && [d.row.transaction_id, d.pan, d.tan, d.deductee, d.challan, d.evidence].join(' ').toLowerCase().includes(search.toLowerCase()));
  const current = Math.min(page, Math.max(1, Math.ceil(filtered.length / 25)));
  return <><div className="filter-bar"><label>Search results<input aria-label="Search results" value={search} placeholder="Liability, PAN, TAN, deductee, challan, evidence" onChange={e => { setSearch(e.target.value); setPage(1); }} /></label>{keys.map(k => <label key={k}>{({ fy: 'Financial Year', pan: 'PAN', tan: 'TAN' } as Record<string, string>)[k] || label(k)}<select aria-label={`Filter ${k}`} value={filters[k] || ''} onChange={e => { setFilters({ ...filters, [k]: e.target.value }); setPage(1); }}><option value="">All</option>{Array.from(new Set(data.map(d => d[k]).filter(Boolean))).map(v => <option key={v} value={v}>{['overall', 'timeliness', 'relationship'].includes(k) ? label(v) : v}</option>)}</select></label>)}<label>Attention<select value={filters.attention || ''} onChange={e => { setFilters({ ...filters, attention: e.target.value }); setPage(1); }}><option value="">All results</option><option value="review">Review Required</option><option value="exception">Exceptions</option></select></label><button className="text-button" onClick={() => { setFilters({}); setSearch(''); setPage(1); }}>Clear filters</button></div>
    <div className="table-scroll"><table className="data-table"><caption className="sr-only">Deposit compliance results</caption><thead><tr>{['Liability / Transaction', 'Deductee / PAN', 'TAN', 'Expected TDS', 'Evidence / Challan', 'Deposit Amount', 'Deposit Date', 'Deduction Date', 'Timeliness', 'Relationship', 'Overall Status', 'Reason'].map(h => <th key={h}>{h}</th>)}</tr></thead><tbody>{filtered.slice((current - 1) * 25, current * 25).map(d => <tr key={d.row.transaction_id} onClick={() => onDetail(d.row)}><td><button className="text-button" onClick={e => { e.stopPropagation(); onDetail(d.row); }}>{d.row.transaction_id}</button></td><td>{provided(d.deductee)}<small className="phase5-block">{provided(d.pan)}</small></td><td>{provided(d.tan)}</td><td>{money(d.row.expected_tds)}</td><td>{provided(d.evidence)}<small className="phase5-block">{provided(d.challan)}</small></td><td>{money(d.row.deposited_tds)}</td><td>{d.row.evidence_entries.map(e => provided(e.deposit_date)).join(', ') || 'Not Provided'}</td><td>{provided(context.timing.find(t => t.transaction_id === d.row.transaction_id)?.actual_deduction_date)}</td><td><Badge value={d.row.timeliness_status} /></td><td><Badge value={d.row.relationship_status} /></td><td><Badge value={d.overall} /></td><td className="phase5-reason">{d.row.reason_code ? label(d.row.reason_code) : d.row.reason || 'Not Provided'}</td></tr>)}</tbody></table></div>{!filtered.length && <EmptyState title="No matching results" text="Change the filters or run a preview for the selected inputs." />}<Pagination page={current} pageSize={25} total={filtered.length} onPage={setPage} />
  </>;
}
